//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAN_XLIII_Kristina_Garcia_Francisco.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwUser
    {
        public int UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string JMBG { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string BankAccount { get; set; }
        public string Email { get; set; }
        public string Salary { get; set; }
        public string Position { get; set; }
        public string Username { get; set; }
        public string UserPassword { get; set; }
    }
}
